version: 2

models:
  - name: mart_gmv_by_category
    description: "Витрина выручки по категориям"
    columns:
      - name: category_name
        description: "Название категории"
        tests:
          - unique
          - not_null
      - name: total_gmv
        description: "Общая выручка по категории"
        tests:
          - not_null

  - name: mart_retention
    description: "Когортный анализ удержания клиентов"
    columns:
      - name: cohort_month
        tests:
          - not_null
      - name: activity_month
        tests:
          - not_null
      - name: retention_rate
        tests:
          - not_null          